# environment.yml
# for running mlflow experiments locally
name: pokemon-mlflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - imbalanced-learn
  - ipython
  - ipykernel
  - ipywidgets
  - jupyterlab
  - pip
  - pip:
      - mlflow
